### ISSUE TITLE
status update 20201029

### ISSUE THREAD

**Issue by DarrenWong** [zengrey/201_ENG1003_AAE_GP7#2]
Any update? about tasks 1,2 and 3.

**Comment by zengrey** [comment]
for task1, we got the plane with min cost is polyu-a380with the cost2941.417. for task 2.1 ,we got the answer that when cf=ct=20, the plane will have the min cost(29504.167).for task2.2, i got the answer that when he cf=2,dealt f is 9, ct=8. dealt t=1,the cost can be min and  it seems that dealt fa and dealt ta just don't affect the cost. i'm still waiting for my group mates to confirm the answer.

**Comment by DarrenWong** [comment]
Got it and thanks
